name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: dev code
        uses: actions/checkout@v2
      - name: deploy to heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
          docker_build_args: |
            NODE_ENV
            REACT_APP_TURN_CREDENTIALS
        env:
          NODE_ENV: production
          REACT_APP_TURN_CREDENTIALS: ${{secrets.TURN_CREDENTIALS}}